-- Table: public.CssColors

-- DROP TABLE IF EXISTS public."CssColors";

CREATE TABLE IF NOT EXISTS public."CssColors"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Value" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_CssColors" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."CssColors"
    OWNER to postgres;